numbers: Add proper safety to operator overloading
graphprotocol/graph-ts pull request #204
Opened 2021-09-08 17:43 UTC by otaviopace

2021-09-08 21:28 UTC, lutter requested changes
I don't think that silently coercing `null` to `0` is the right thing to do - if these get called with a `null` it's probably some coding error, and `0` is probably not the value that was intended to be used in the calculation, leading to calculations that are silently wrong.

2021-09-08 21:47 UTC, otaviopace commented
Ok @lutter , I'll throw an error instead! I thought about this following this path before, but then I thought it would be easier for subgraph developers to upgrade the AS version.

The only problem right now is that they can only know this at runtime. I'll open an issue in the AS compiler so that we can have this error at compile time as well (better feedback loop for subgraph devs 🙂 ).

Also, I'll document this in the Migration Guide since it's a known issue, at least they can read it there and try to fix before it happens at runtime.

2021-09-09 05:03 UTC, lutter approved these changes

2021-09-09 05:04 UTC, lutter commented
Yes, I think doing it this way is safer; and this should absolutely be a compile-time error. But at least, using asserts here, the current workaround is safe in terms of not doing math that might be wrong.

2021-09-09 11:03 UTC, merged